# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'BayAreaBuses' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps', '4.2.0'
  pod 'GooglePlaces', '4.2.0'
  # Pods for BayAreaBuses

  target 'BayAreaBusesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BayAreaBusesUITests' do
    # Pods for testing
  end

end
